language: python

cache: pip

python:
    - "2.7"
    - "pypy"
    - "3.5"
    - "3.6"

matrix:
    include:
      - python: "3.7"
        dist: xenial    # required for >= Python 3.7
      - python: "3.7-dev"
        dist: xenial    # required for >= Python 3.7
      - python: "3.8-dev"
        dist: xenial    # required for >= Python 3.7

install:
  - pip install tox-travis
script:
  - tox

notifications:
  on_success: never
  on_failure: always
