language: python

sudo: false
cache: pip

python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6-dev"
    - "3.7-dev"

install:
  - pip install tox-travis
script:
  - tox

notifications:
  on_success: never
  on_failure: always
